// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cloud.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace tobeh.Valmar {

  /// <summary>Holder for reflection information generated from cloud.proto</summary>
  public static partial class CloudReflection {

    #region Descriptor
    /// <summary>File descriptor for cloud.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CloudReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtjbG91ZC5wcm90bxIFY2xvdWQaG2dvb2dsZS9wcm90b2J1Zi9lbXB0eS5w",
            "cm90bxoeZ29vZ2xlL3Byb3RvYnVmL3dyYXBwZXJzLnByb3RvIsMDChJTZWFy",
            "Y2hDbG91ZE1lc3NhZ2USDAoEcGFnZRgBIAEoBRIQCghwYWdlU2l6ZRgCIAEo",
            "BRISCgpvd25lckxvZ2luGAMgASgFEjEKC2F1dGhvclF1ZXJ5GAQgASgLMhwu",
            "Z29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlEjMKDWxhbmd1YWdlUXVlcnkY",
            "BSABKAsyHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWUSNwoSY3JlYXRl",
            "ZEJlZm9yZVF1ZXJ5GAYgASgLMhsuZ29vZ2xlLnByb3RvYnVmLkludDY0VmFs",
            "dWUSNgoRY3JlYXRlZEFmdGVyUXVlcnkYByABKAsyGy5nb29nbGUucHJvdG9i",
            "dWYuSW50NjRWYWx1ZRI+ChpjcmVhdGVkSW5Qcml2YXRlTG9iYnlRdWVyeRgI",
            "IAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5Cb29sVmFsdWUSLgoKaXNPd25RdWVy",
            "eRgJIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5Cb29sVmFsdWUSMAoKdGl0bGVR",
            "dWVyeRgKIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZSJ9ChFD",
            "bG91ZEltYWdlTWVzc2FnZRIKCgJpZBgBIAEoAxIQCghpbWFnZVVybBgCIAEo",
            "CRIPCgdtZXRhVXJsGAMgASgJEhMKC2NvbW1hbmRzVXJsGAQgASgJEiQKBHRh",
            "Z3MYBSABKAsyFi5jbG91ZC5DbG91ZFRhZ01lc3NhZ2UilwEKD0Nsb3VkVGFn",
            "TWVzc2FnZRINCgV0aXRsZRgBIAEoCRIOCgZhdXRob3IYAiABKAkSEAoIbGFu",
            "Z3VhZ2UYAyABKAkSEQoJY3JlYXRlZEF0GAQgASgDEh0KFWNyZWF0ZWRJblBy",
            "aXZhdGVMb2JieRgFIAEoCBINCgVpc093bhgGIAEoCBISCgpvd25lckxvZ2lu",
            "GAcgASgFIiEKE0Nsb3VkSW1hZ2VJZE1lc3NhZ2USCgoCaWQYASABKAMiOQoX",
            "R2V0Q2xvdWRUYWdzQnlJZE1lc3NhZ2USCgoCaWQYASABKAMSEgoKb3duZXJM",
            "b2dpbhgCIAEoBSJTChdMaW5rSW1hZ2VUb0F3YXJkTWVzc2FnZRIKCgJpZBgB",
            "IAEoAxISCgpvd25lckxvZ2luGAIgASgFEhgKEGF3YXJkSW52ZW50b3J5SWQY",
            "AyABKAUiOQoWRGVsZXRlQ2xvdWRUYWdzTWVzc2FnZRISCgpvd25lckxvZ2lu",
            "GAEgASgFEgsKA2lkcxgCIAMoAzL2AgoFQ2xvdWQSRAoLU2VhcmNoQ2xvdWQS",
            "GS5jbG91ZC5TZWFyY2hDbG91ZE1lc3NhZ2UaGC5jbG91ZC5DbG91ZEltYWdl",
            "TWVzc2FnZTABEkMKDVNhdmVDbG91ZFRhZ3MSFi5jbG91ZC5DbG91ZFRhZ01l",
            "c3NhZ2UaGi5jbG91ZC5DbG91ZEltYWdlSWRNZXNzYWdlEkwKEEdldENsb3Vk",
            "VGFnc0J5SWQSHi5jbG91ZC5HZXRDbG91ZFRhZ3NCeUlkTWVzc2FnZRoYLmNs",
            "b3VkLkNsb3VkSW1hZ2VNZXNzYWdlEkgKD0RlbGV0ZUNsb3VkVGFncxIdLmNs",
            "b3VkLkRlbGV0ZUNsb3VkVGFnc01lc3NhZ2UaFi5nb29nbGUucHJvdG9idWYu",
            "RW1wdHkSSgoQTGlua0ltYWdlVG9Bd2FyZBIeLmNsb3VkLkxpbmtJbWFnZVRv",
            "QXdhcmRNZXNzYWdlGhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5Qg+qAgx0b2Jl",
            "aC5WYWxtYXJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::tobeh.Valmar.SearchCloudMessage), global::tobeh.Valmar.SearchCloudMessage.Parser, new[]{ "Page", "PageSize", "OwnerLogin", "AuthorQuery", "LanguageQuery", "CreatedBeforeQuery", "CreatedAfterQuery", "CreatedInPrivateLobbyQuery", "IsOwnQuery", "TitleQuery" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::tobeh.Valmar.CloudImageMessage), global::tobeh.Valmar.CloudImageMessage.Parser, new[]{ "Id", "ImageUrl", "MetaUrl", "CommandsUrl", "Tags" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::tobeh.Valmar.CloudTagMessage), global::tobeh.Valmar.CloudTagMessage.Parser, new[]{ "Title", "Author", "Language", "CreatedAt", "CreatedInPrivateLobby", "IsOwn", "OwnerLogin" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::tobeh.Valmar.CloudImageIdMessage), global::tobeh.Valmar.CloudImageIdMessage.Parser, new[]{ "Id" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::tobeh.Valmar.GetCloudTagsByIdMessage), global::tobeh.Valmar.GetCloudTagsByIdMessage.Parser, new[]{ "Id", "OwnerLogin" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::tobeh.Valmar.LinkImageToAwardMessage), global::tobeh.Valmar.LinkImageToAwardMessage.Parser, new[]{ "Id", "OwnerLogin", "AwardInventoryId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::tobeh.Valmar.DeleteCloudTagsMessage), global::tobeh.Valmar.DeleteCloudTagsMessage.Parser, new[]{ "OwnerLogin", "Ids" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SearchCloudMessage : pb::IMessage<SearchCloudMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SearchCloudMessage> _parser = new pb::MessageParser<SearchCloudMessage>(() => new SearchCloudMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SearchCloudMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::tobeh.Valmar.CloudReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SearchCloudMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SearchCloudMessage(SearchCloudMessage other) : this() {
      page_ = other.page_;
      pageSize_ = other.pageSize_;
      ownerLogin_ = other.ownerLogin_;
      AuthorQuery = other.AuthorQuery;
      LanguageQuery = other.LanguageQuery;
      CreatedBeforeQuery = other.CreatedBeforeQuery;
      CreatedAfterQuery = other.CreatedAfterQuery;
      CreatedInPrivateLobbyQuery = other.CreatedInPrivateLobbyQuery;
      IsOwnQuery = other.IsOwnQuery;
      TitleQuery = other.TitleQuery;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SearchCloudMessage Clone() {
      return new SearchCloudMessage(this);
    }

    /// <summary>Field number for the "page" field.</summary>
    public const int PageFieldNumber = 1;
    private int page_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Page {
      get { return page_; }
      set {
        page_ = value;
      }
    }

    /// <summary>Field number for the "pageSize" field.</summary>
    public const int PageSizeFieldNumber = 2;
    private int pageSize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PageSize {
      get { return pageSize_; }
      set {
        pageSize_ = value;
      }
    }

    /// <summary>Field number for the "ownerLogin" field.</summary>
    public const int OwnerLoginFieldNumber = 3;
    private int ownerLogin_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int OwnerLogin {
      get { return ownerLogin_; }
      set {
        ownerLogin_ = value;
      }
    }

    /// <summary>Field number for the "authorQuery" field.</summary>
    public const int AuthorQueryFieldNumber = 4;
    private static readonly pb::FieldCodec<string> _single_authorQuery_codec = pb::FieldCodec.ForClassWrapper<string>(34);
    private string authorQuery_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AuthorQuery {
      get { return authorQuery_; }
      set {
        authorQuery_ = value;
      }
    }


    /// <summary>Field number for the "languageQuery" field.</summary>
    public const int LanguageQueryFieldNumber = 5;
    private static readonly pb::FieldCodec<string> _single_languageQuery_codec = pb::FieldCodec.ForClassWrapper<string>(42);
    private string languageQuery_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LanguageQuery {
      get { return languageQuery_; }
      set {
        languageQuery_ = value;
      }
    }


    /// <summary>Field number for the "createdBeforeQuery" field.</summary>
    public const int CreatedBeforeQueryFieldNumber = 6;
    private static readonly pb::FieldCodec<long?> _single_createdBeforeQuery_codec = pb::FieldCodec.ForStructWrapper<long>(50);
    private long? createdBeforeQuery_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long? CreatedBeforeQuery {
      get { return createdBeforeQuery_; }
      set {
        createdBeforeQuery_ = value;
      }
    }


    /// <summary>Field number for the "createdAfterQuery" field.</summary>
    public const int CreatedAfterQueryFieldNumber = 7;
    private static readonly pb::FieldCodec<long?> _single_createdAfterQuery_codec = pb::FieldCodec.ForStructWrapper<long>(58);
    private long? createdAfterQuery_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long? CreatedAfterQuery {
      get { return createdAfterQuery_; }
      set {
        createdAfterQuery_ = value;
      }
    }


    /// <summary>Field number for the "createdInPrivateLobbyQuery" field.</summary>
    public const int CreatedInPrivateLobbyQueryFieldNumber = 8;
    private static readonly pb::FieldCodec<bool?> _single_createdInPrivateLobbyQuery_codec = pb::FieldCodec.ForStructWrapper<bool>(66);
    private bool? createdInPrivateLobbyQuery_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool? CreatedInPrivateLobbyQuery {
      get { return createdInPrivateLobbyQuery_; }
      set {
        createdInPrivateLobbyQuery_ = value;
      }
    }


    /// <summary>Field number for the "isOwnQuery" field.</summary>
    public const int IsOwnQueryFieldNumber = 9;
    private static readonly pb::FieldCodec<bool?> _single_isOwnQuery_codec = pb::FieldCodec.ForStructWrapper<bool>(74);
    private bool? isOwnQuery_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool? IsOwnQuery {
      get { return isOwnQuery_; }
      set {
        isOwnQuery_ = value;
      }
    }


    /// <summary>Field number for the "titleQuery" field.</summary>
    public const int TitleQueryFieldNumber = 10;
    private static readonly pb::FieldCodec<string> _single_titleQuery_codec = pb::FieldCodec.ForClassWrapper<string>(82);
    private string titleQuery_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TitleQuery {
      get { return titleQuery_; }
      set {
        titleQuery_ = value;
      }
    }


    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SearchCloudMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SearchCloudMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Page != other.Page) return false;
      if (PageSize != other.PageSize) return false;
      if (OwnerLogin != other.OwnerLogin) return false;
      if (AuthorQuery != other.AuthorQuery) return false;
      if (LanguageQuery != other.LanguageQuery) return false;
      if (CreatedBeforeQuery != other.CreatedBeforeQuery) return false;
      if (CreatedAfterQuery != other.CreatedAfterQuery) return false;
      if (CreatedInPrivateLobbyQuery != other.CreatedInPrivateLobbyQuery) return false;
      if (IsOwnQuery != other.IsOwnQuery) return false;
      if (TitleQuery != other.TitleQuery) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Page != 0) hash ^= Page.GetHashCode();
      if (PageSize != 0) hash ^= PageSize.GetHashCode();
      if (OwnerLogin != 0) hash ^= OwnerLogin.GetHashCode();
      if (authorQuery_ != null) hash ^= AuthorQuery.GetHashCode();
      if (languageQuery_ != null) hash ^= LanguageQuery.GetHashCode();
      if (createdBeforeQuery_ != null) hash ^= CreatedBeforeQuery.GetHashCode();
      if (createdAfterQuery_ != null) hash ^= CreatedAfterQuery.GetHashCode();
      if (createdInPrivateLobbyQuery_ != null) hash ^= CreatedInPrivateLobbyQuery.GetHashCode();
      if (isOwnQuery_ != null) hash ^= IsOwnQuery.GetHashCode();
      if (titleQuery_ != null) hash ^= TitleQuery.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Page != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Page);
      }
      if (PageSize != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(PageSize);
      }
      if (OwnerLogin != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(OwnerLogin);
      }
      if (authorQuery_ != null) {
        _single_authorQuery_codec.WriteTagAndValue(output, AuthorQuery);
      }
      if (languageQuery_ != null) {
        _single_languageQuery_codec.WriteTagAndValue(output, LanguageQuery);
      }
      if (createdBeforeQuery_ != null) {
        _single_createdBeforeQuery_codec.WriteTagAndValue(output, CreatedBeforeQuery);
      }
      if (createdAfterQuery_ != null) {
        _single_createdAfterQuery_codec.WriteTagAndValue(output, CreatedAfterQuery);
      }
      if (createdInPrivateLobbyQuery_ != null) {
        _single_createdInPrivateLobbyQuery_codec.WriteTagAndValue(output, CreatedInPrivateLobbyQuery);
      }
      if (isOwnQuery_ != null) {
        _single_isOwnQuery_codec.WriteTagAndValue(output, IsOwnQuery);
      }
      if (titleQuery_ != null) {
        _single_titleQuery_codec.WriteTagAndValue(output, TitleQuery);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Page != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Page);
      }
      if (PageSize != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(PageSize);
      }
      if (OwnerLogin != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(OwnerLogin);
      }
      if (authorQuery_ != null) {
        _single_authorQuery_codec.WriteTagAndValue(ref output, AuthorQuery);
      }
      if (languageQuery_ != null) {
        _single_languageQuery_codec.WriteTagAndValue(ref output, LanguageQuery);
      }
      if (createdBeforeQuery_ != null) {
        _single_createdBeforeQuery_codec.WriteTagAndValue(ref output, CreatedBeforeQuery);
      }
      if (createdAfterQuery_ != null) {
        _single_createdAfterQuery_codec.WriteTagAndValue(ref output, CreatedAfterQuery);
      }
      if (createdInPrivateLobbyQuery_ != null) {
        _single_createdInPrivateLobbyQuery_codec.WriteTagAndValue(ref output, CreatedInPrivateLobbyQuery);
      }
      if (isOwnQuery_ != null) {
        _single_isOwnQuery_codec.WriteTagAndValue(ref output, IsOwnQuery);
      }
      if (titleQuery_ != null) {
        _single_titleQuery_codec.WriteTagAndValue(ref output, TitleQuery);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Page != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Page);
      }
      if (PageSize != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PageSize);
      }
      if (OwnerLogin != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(OwnerLogin);
      }
      if (authorQuery_ != null) {
        size += _single_authorQuery_codec.CalculateSizeWithTag(AuthorQuery);
      }
      if (languageQuery_ != null) {
        size += _single_languageQuery_codec.CalculateSizeWithTag(LanguageQuery);
      }
      if (createdBeforeQuery_ != null) {
        size += _single_createdBeforeQuery_codec.CalculateSizeWithTag(CreatedBeforeQuery);
      }
      if (createdAfterQuery_ != null) {
        size += _single_createdAfterQuery_codec.CalculateSizeWithTag(CreatedAfterQuery);
      }
      if (createdInPrivateLobbyQuery_ != null) {
        size += _single_createdInPrivateLobbyQuery_codec.CalculateSizeWithTag(CreatedInPrivateLobbyQuery);
      }
      if (isOwnQuery_ != null) {
        size += _single_isOwnQuery_codec.CalculateSizeWithTag(IsOwnQuery);
      }
      if (titleQuery_ != null) {
        size += _single_titleQuery_codec.CalculateSizeWithTag(TitleQuery);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SearchCloudMessage other) {
      if (other == null) {
        return;
      }
      if (other.Page != 0) {
        Page = other.Page;
      }
      if (other.PageSize != 0) {
        PageSize = other.PageSize;
      }
      if (other.OwnerLogin != 0) {
        OwnerLogin = other.OwnerLogin;
      }
      if (other.authorQuery_ != null) {
        if (authorQuery_ == null || other.AuthorQuery != "") {
          AuthorQuery = other.AuthorQuery;
        }
      }
      if (other.languageQuery_ != null) {
        if (languageQuery_ == null || other.LanguageQuery != "") {
          LanguageQuery = other.LanguageQuery;
        }
      }
      if (other.createdBeforeQuery_ != null) {
        if (createdBeforeQuery_ == null || other.CreatedBeforeQuery != 0L) {
          CreatedBeforeQuery = other.CreatedBeforeQuery;
        }
      }
      if (other.createdAfterQuery_ != null) {
        if (createdAfterQuery_ == null || other.CreatedAfterQuery != 0L) {
          CreatedAfterQuery = other.CreatedAfterQuery;
        }
      }
      if (other.createdInPrivateLobbyQuery_ != null) {
        if (createdInPrivateLobbyQuery_ == null || other.CreatedInPrivateLobbyQuery != false) {
          CreatedInPrivateLobbyQuery = other.CreatedInPrivateLobbyQuery;
        }
      }
      if (other.isOwnQuery_ != null) {
        if (isOwnQuery_ == null || other.IsOwnQuery != false) {
          IsOwnQuery = other.IsOwnQuery;
        }
      }
      if (other.titleQuery_ != null) {
        if (titleQuery_ == null || other.TitleQuery != "") {
          TitleQuery = other.TitleQuery;
        }
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Page = input.ReadInt32();
            break;
          }
          case 16: {
            PageSize = input.ReadInt32();
            break;
          }
          case 24: {
            OwnerLogin = input.ReadInt32();
            break;
          }
          case 34: {
            string value = _single_authorQuery_codec.Read(input);
            if (authorQuery_ == null || value != "") {
              AuthorQuery = value;
            }
            break;
          }
          case 42: {
            string value = _single_languageQuery_codec.Read(input);
            if (languageQuery_ == null || value != "") {
              LanguageQuery = value;
            }
            break;
          }
          case 50: {
            long? value = _single_createdBeforeQuery_codec.Read(input);
            if (createdBeforeQuery_ == null || value != 0L) {
              CreatedBeforeQuery = value;
            }
            break;
          }
          case 58: {
            long? value = _single_createdAfterQuery_codec.Read(input);
            if (createdAfterQuery_ == null || value != 0L) {
              CreatedAfterQuery = value;
            }
            break;
          }
          case 66: {
            bool? value = _single_createdInPrivateLobbyQuery_codec.Read(input);
            if (createdInPrivateLobbyQuery_ == null || value != false) {
              CreatedInPrivateLobbyQuery = value;
            }
            break;
          }
          case 74: {
            bool? value = _single_isOwnQuery_codec.Read(input);
            if (isOwnQuery_ == null || value != false) {
              IsOwnQuery = value;
            }
            break;
          }
          case 82: {
            string value = _single_titleQuery_codec.Read(input);
            if (titleQuery_ == null || value != "") {
              TitleQuery = value;
            }
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Page = input.ReadInt32();
            break;
          }
          case 16: {
            PageSize = input.ReadInt32();
            break;
          }
          case 24: {
            OwnerLogin = input.ReadInt32();
            break;
          }
          case 34: {
            string value = _single_authorQuery_codec.Read(ref input);
            if (authorQuery_ == null || value != "") {
              AuthorQuery = value;
            }
            break;
          }
          case 42: {
            string value = _single_languageQuery_codec.Read(ref input);
            if (languageQuery_ == null || value != "") {
              LanguageQuery = value;
            }
            break;
          }
          case 50: {
            long? value = _single_createdBeforeQuery_codec.Read(ref input);
            if (createdBeforeQuery_ == null || value != 0L) {
              CreatedBeforeQuery = value;
            }
            break;
          }
          case 58: {
            long? value = _single_createdAfterQuery_codec.Read(ref input);
            if (createdAfterQuery_ == null || value != 0L) {
              CreatedAfterQuery = value;
            }
            break;
          }
          case 66: {
            bool? value = _single_createdInPrivateLobbyQuery_codec.Read(ref input);
            if (createdInPrivateLobbyQuery_ == null || value != false) {
              CreatedInPrivateLobbyQuery = value;
            }
            break;
          }
          case 74: {
            bool? value = _single_isOwnQuery_codec.Read(ref input);
            if (isOwnQuery_ == null || value != false) {
              IsOwnQuery = value;
            }
            break;
          }
          case 82: {
            string value = _single_titleQuery_codec.Read(ref input);
            if (titleQuery_ == null || value != "") {
              TitleQuery = value;
            }
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CloudImageMessage : pb::IMessage<CloudImageMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CloudImageMessage> _parser = new pb::MessageParser<CloudImageMessage>(() => new CloudImageMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CloudImageMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::tobeh.Valmar.CloudReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CloudImageMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CloudImageMessage(CloudImageMessage other) : this() {
      id_ = other.id_;
      imageUrl_ = other.imageUrl_;
      metaUrl_ = other.metaUrl_;
      commandsUrl_ = other.commandsUrl_;
      tags_ = other.tags_ != null ? other.tags_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CloudImageMessage Clone() {
      return new CloudImageMessage(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "imageUrl" field.</summary>
    public const int ImageUrlFieldNumber = 2;
    private string imageUrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ImageUrl {
      get { return imageUrl_; }
      set {
        imageUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "metaUrl" field.</summary>
    public const int MetaUrlFieldNumber = 3;
    private string metaUrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MetaUrl {
      get { return metaUrl_; }
      set {
        metaUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "commandsUrl" field.</summary>
    public const int CommandsUrlFieldNumber = 4;
    private string commandsUrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CommandsUrl {
      get { return commandsUrl_; }
      set {
        commandsUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tags" field.</summary>
    public const int TagsFieldNumber = 5;
    private global::tobeh.Valmar.CloudTagMessage tags_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::tobeh.Valmar.CloudTagMessage Tags {
      get { return tags_; }
      set {
        tags_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CloudImageMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CloudImageMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (ImageUrl != other.ImageUrl) return false;
      if (MetaUrl != other.MetaUrl) return false;
      if (CommandsUrl != other.CommandsUrl) return false;
      if (!object.Equals(Tags, other.Tags)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (ImageUrl.Length != 0) hash ^= ImageUrl.GetHashCode();
      if (MetaUrl.Length != 0) hash ^= MetaUrl.GetHashCode();
      if (CommandsUrl.Length != 0) hash ^= CommandsUrl.GetHashCode();
      if (tags_ != null) hash ^= Tags.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (ImageUrl.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ImageUrl);
      }
      if (MetaUrl.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(MetaUrl);
      }
      if (CommandsUrl.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(CommandsUrl);
      }
      if (tags_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Tags);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (ImageUrl.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ImageUrl);
      }
      if (MetaUrl.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(MetaUrl);
      }
      if (CommandsUrl.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(CommandsUrl);
      }
      if (tags_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Tags);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (ImageUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ImageUrl);
      }
      if (MetaUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MetaUrl);
      }
      if (CommandsUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CommandsUrl);
      }
      if (tags_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Tags);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CloudImageMessage other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.ImageUrl.Length != 0) {
        ImageUrl = other.ImageUrl;
      }
      if (other.MetaUrl.Length != 0) {
        MetaUrl = other.MetaUrl;
      }
      if (other.CommandsUrl.Length != 0) {
        CommandsUrl = other.CommandsUrl;
      }
      if (other.tags_ != null) {
        if (tags_ == null) {
          Tags = new global::tobeh.Valmar.CloudTagMessage();
        }
        Tags.MergeFrom(other.Tags);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            ImageUrl = input.ReadString();
            break;
          }
          case 26: {
            MetaUrl = input.ReadString();
            break;
          }
          case 34: {
            CommandsUrl = input.ReadString();
            break;
          }
          case 42: {
            if (tags_ == null) {
              Tags = new global::tobeh.Valmar.CloudTagMessage();
            }
            input.ReadMessage(Tags);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            ImageUrl = input.ReadString();
            break;
          }
          case 26: {
            MetaUrl = input.ReadString();
            break;
          }
          case 34: {
            CommandsUrl = input.ReadString();
            break;
          }
          case 42: {
            if (tags_ == null) {
              Tags = new global::tobeh.Valmar.CloudTagMessage();
            }
            input.ReadMessage(Tags);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CloudTagMessage : pb::IMessage<CloudTagMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CloudTagMessage> _parser = new pb::MessageParser<CloudTagMessage>(() => new CloudTagMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CloudTagMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::tobeh.Valmar.CloudReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CloudTagMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CloudTagMessage(CloudTagMessage other) : this() {
      title_ = other.title_;
      author_ = other.author_;
      language_ = other.language_;
      createdAt_ = other.createdAt_;
      createdInPrivateLobby_ = other.createdInPrivateLobby_;
      isOwn_ = other.isOwn_;
      ownerLogin_ = other.ownerLogin_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CloudTagMessage Clone() {
      return new CloudTagMessage(this);
    }

    /// <summary>Field number for the "title" field.</summary>
    public const int TitleFieldNumber = 1;
    private string title_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Title {
      get { return title_; }
      set {
        title_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "author" field.</summary>
    public const int AuthorFieldNumber = 2;
    private string author_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Author {
      get { return author_; }
      set {
        author_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "language" field.</summary>
    public const int LanguageFieldNumber = 3;
    private string language_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Language {
      get { return language_; }
      set {
        language_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "createdAt" field.</summary>
    public const int CreatedAtFieldNumber = 4;
    private long createdAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long CreatedAt {
      get { return createdAt_; }
      set {
        createdAt_ = value;
      }
    }

    /// <summary>Field number for the "createdInPrivateLobby" field.</summary>
    public const int CreatedInPrivateLobbyFieldNumber = 5;
    private bool createdInPrivateLobby_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool CreatedInPrivateLobby {
      get { return createdInPrivateLobby_; }
      set {
        createdInPrivateLobby_ = value;
      }
    }

    /// <summary>Field number for the "isOwn" field.</summary>
    public const int IsOwnFieldNumber = 6;
    private bool isOwn_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsOwn {
      get { return isOwn_; }
      set {
        isOwn_ = value;
      }
    }

    /// <summary>Field number for the "ownerLogin" field.</summary>
    public const int OwnerLoginFieldNumber = 7;
    private int ownerLogin_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int OwnerLogin {
      get { return ownerLogin_; }
      set {
        ownerLogin_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CloudTagMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CloudTagMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Title != other.Title) return false;
      if (Author != other.Author) return false;
      if (Language != other.Language) return false;
      if (CreatedAt != other.CreatedAt) return false;
      if (CreatedInPrivateLobby != other.CreatedInPrivateLobby) return false;
      if (IsOwn != other.IsOwn) return false;
      if (OwnerLogin != other.OwnerLogin) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Title.Length != 0) hash ^= Title.GetHashCode();
      if (Author.Length != 0) hash ^= Author.GetHashCode();
      if (Language.Length != 0) hash ^= Language.GetHashCode();
      if (CreatedAt != 0L) hash ^= CreatedAt.GetHashCode();
      if (CreatedInPrivateLobby != false) hash ^= CreatedInPrivateLobby.GetHashCode();
      if (IsOwn != false) hash ^= IsOwn.GetHashCode();
      if (OwnerLogin != 0) hash ^= OwnerLogin.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Title.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Title);
      }
      if (Author.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Author);
      }
      if (Language.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Language);
      }
      if (CreatedAt != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(CreatedAt);
      }
      if (CreatedInPrivateLobby != false) {
        output.WriteRawTag(40);
        output.WriteBool(CreatedInPrivateLobby);
      }
      if (IsOwn != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsOwn);
      }
      if (OwnerLogin != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(OwnerLogin);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Title.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Title);
      }
      if (Author.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Author);
      }
      if (Language.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Language);
      }
      if (CreatedAt != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(CreatedAt);
      }
      if (CreatedInPrivateLobby != false) {
        output.WriteRawTag(40);
        output.WriteBool(CreatedInPrivateLobby);
      }
      if (IsOwn != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsOwn);
      }
      if (OwnerLogin != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(OwnerLogin);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Title.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Title);
      }
      if (Author.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Author);
      }
      if (Language.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Language);
      }
      if (CreatedAt != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CreatedAt);
      }
      if (CreatedInPrivateLobby != false) {
        size += 1 + 1;
      }
      if (IsOwn != false) {
        size += 1 + 1;
      }
      if (OwnerLogin != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(OwnerLogin);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CloudTagMessage other) {
      if (other == null) {
        return;
      }
      if (other.Title.Length != 0) {
        Title = other.Title;
      }
      if (other.Author.Length != 0) {
        Author = other.Author;
      }
      if (other.Language.Length != 0) {
        Language = other.Language;
      }
      if (other.CreatedAt != 0L) {
        CreatedAt = other.CreatedAt;
      }
      if (other.CreatedInPrivateLobby != false) {
        CreatedInPrivateLobby = other.CreatedInPrivateLobby;
      }
      if (other.IsOwn != false) {
        IsOwn = other.IsOwn;
      }
      if (other.OwnerLogin != 0) {
        OwnerLogin = other.OwnerLogin;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Title = input.ReadString();
            break;
          }
          case 18: {
            Author = input.ReadString();
            break;
          }
          case 26: {
            Language = input.ReadString();
            break;
          }
          case 32: {
            CreatedAt = input.ReadInt64();
            break;
          }
          case 40: {
            CreatedInPrivateLobby = input.ReadBool();
            break;
          }
          case 48: {
            IsOwn = input.ReadBool();
            break;
          }
          case 56: {
            OwnerLogin = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Title = input.ReadString();
            break;
          }
          case 18: {
            Author = input.ReadString();
            break;
          }
          case 26: {
            Language = input.ReadString();
            break;
          }
          case 32: {
            CreatedAt = input.ReadInt64();
            break;
          }
          case 40: {
            CreatedInPrivateLobby = input.ReadBool();
            break;
          }
          case 48: {
            IsOwn = input.ReadBool();
            break;
          }
          case 56: {
            OwnerLogin = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CloudImageIdMessage : pb::IMessage<CloudImageIdMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CloudImageIdMessage> _parser = new pb::MessageParser<CloudImageIdMessage>(() => new CloudImageIdMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CloudImageIdMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::tobeh.Valmar.CloudReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CloudImageIdMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CloudImageIdMessage(CloudImageIdMessage other) : this() {
      id_ = other.id_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CloudImageIdMessage Clone() {
      return new CloudImageIdMessage(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CloudImageIdMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CloudImageIdMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CloudImageIdMessage other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class GetCloudTagsByIdMessage : pb::IMessage<GetCloudTagsByIdMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetCloudTagsByIdMessage> _parser = new pb::MessageParser<GetCloudTagsByIdMessage>(() => new GetCloudTagsByIdMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetCloudTagsByIdMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::tobeh.Valmar.CloudReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetCloudTagsByIdMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetCloudTagsByIdMessage(GetCloudTagsByIdMessage other) : this() {
      id_ = other.id_;
      ownerLogin_ = other.ownerLogin_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetCloudTagsByIdMessage Clone() {
      return new GetCloudTagsByIdMessage(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "ownerLogin" field.</summary>
    public const int OwnerLoginFieldNumber = 2;
    private int ownerLogin_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int OwnerLogin {
      get { return ownerLogin_; }
      set {
        ownerLogin_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetCloudTagsByIdMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetCloudTagsByIdMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (OwnerLogin != other.OwnerLogin) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (OwnerLogin != 0) hash ^= OwnerLogin.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (OwnerLogin != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(OwnerLogin);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (OwnerLogin != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(OwnerLogin);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (OwnerLogin != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(OwnerLogin);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetCloudTagsByIdMessage other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.OwnerLogin != 0) {
        OwnerLogin = other.OwnerLogin;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 16: {
            OwnerLogin = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 16: {
            OwnerLogin = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class LinkImageToAwardMessage : pb::IMessage<LinkImageToAwardMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LinkImageToAwardMessage> _parser = new pb::MessageParser<LinkImageToAwardMessage>(() => new LinkImageToAwardMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LinkImageToAwardMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::tobeh.Valmar.CloudReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LinkImageToAwardMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LinkImageToAwardMessage(LinkImageToAwardMessage other) : this() {
      id_ = other.id_;
      ownerLogin_ = other.ownerLogin_;
      awardInventoryId_ = other.awardInventoryId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LinkImageToAwardMessage Clone() {
      return new LinkImageToAwardMessage(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "ownerLogin" field.</summary>
    public const int OwnerLoginFieldNumber = 2;
    private int ownerLogin_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int OwnerLogin {
      get { return ownerLogin_; }
      set {
        ownerLogin_ = value;
      }
    }

    /// <summary>Field number for the "awardInventoryId" field.</summary>
    public const int AwardInventoryIdFieldNumber = 3;
    private int awardInventoryId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AwardInventoryId {
      get { return awardInventoryId_; }
      set {
        awardInventoryId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LinkImageToAwardMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LinkImageToAwardMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (OwnerLogin != other.OwnerLogin) return false;
      if (AwardInventoryId != other.AwardInventoryId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (OwnerLogin != 0) hash ^= OwnerLogin.GetHashCode();
      if (AwardInventoryId != 0) hash ^= AwardInventoryId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (OwnerLogin != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(OwnerLogin);
      }
      if (AwardInventoryId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(AwardInventoryId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (OwnerLogin != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(OwnerLogin);
      }
      if (AwardInventoryId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(AwardInventoryId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (OwnerLogin != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(OwnerLogin);
      }
      if (AwardInventoryId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AwardInventoryId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LinkImageToAwardMessage other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.OwnerLogin != 0) {
        OwnerLogin = other.OwnerLogin;
      }
      if (other.AwardInventoryId != 0) {
        AwardInventoryId = other.AwardInventoryId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 16: {
            OwnerLogin = input.ReadInt32();
            break;
          }
          case 24: {
            AwardInventoryId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 16: {
            OwnerLogin = input.ReadInt32();
            break;
          }
          case 24: {
            AwardInventoryId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class DeleteCloudTagsMessage : pb::IMessage<DeleteCloudTagsMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DeleteCloudTagsMessage> _parser = new pb::MessageParser<DeleteCloudTagsMessage>(() => new DeleteCloudTagsMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DeleteCloudTagsMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::tobeh.Valmar.CloudReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeleteCloudTagsMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeleteCloudTagsMessage(DeleteCloudTagsMessage other) : this() {
      ownerLogin_ = other.ownerLogin_;
      ids_ = other.ids_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DeleteCloudTagsMessage Clone() {
      return new DeleteCloudTagsMessage(this);
    }

    /// <summary>Field number for the "ownerLogin" field.</summary>
    public const int OwnerLoginFieldNumber = 1;
    private int ownerLogin_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int OwnerLogin {
      get { return ownerLogin_; }
      set {
        ownerLogin_ = value;
      }
    }

    /// <summary>Field number for the "ids" field.</summary>
    public const int IdsFieldNumber = 2;
    private static readonly pb::FieldCodec<long> _repeated_ids_codec
        = pb::FieldCodec.ForInt64(18);
    private readonly pbc::RepeatedField<long> ids_ = new pbc::RepeatedField<long>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<long> Ids {
      get { return ids_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DeleteCloudTagsMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DeleteCloudTagsMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OwnerLogin != other.OwnerLogin) return false;
      if(!ids_.Equals(other.ids_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (OwnerLogin != 0) hash ^= OwnerLogin.GetHashCode();
      hash ^= ids_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (OwnerLogin != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(OwnerLogin);
      }
      ids_.WriteTo(output, _repeated_ids_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (OwnerLogin != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(OwnerLogin);
      }
      ids_.WriteTo(ref output, _repeated_ids_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (OwnerLogin != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(OwnerLogin);
      }
      size += ids_.CalculateSize(_repeated_ids_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DeleteCloudTagsMessage other) {
      if (other == null) {
        return;
      }
      if (other.OwnerLogin != 0) {
        OwnerLogin = other.OwnerLogin;
      }
      ids_.Add(other.ids_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            OwnerLogin = input.ReadInt32();
            break;
          }
          case 18:
          case 16: {
            ids_.AddEntriesFrom(input, _repeated_ids_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            OwnerLogin = input.ReadInt32();
            break;
          }
          case 18:
          case 16: {
            ids_.AddEntriesFrom(ref input, _repeated_ids_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
