version: "3.0"

services:
  valmar:
    container_name: valmar
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    restart: unless-stopped
    volumes:
      - path-to-appsettings.json:/app/appsettings.json
    ports:
      - "8080:8080"
