version: "3.0"

services:
  valmar:
    container_name: valmar
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    restart: no
    environment:
      - DB_DOMAIN_NAME=host.docker.internal
    ports:
      - "8080:8080"
